services:
  app:
    build: 
      context: ./app
    env_file: .env
    volumes:
      - ./app:/app
      - /app/node_modules/
    ports:
      - 8000:8000
      - 6006:6006
    network_mode: host

  api:
    build:
      context: ./api
    env_file: .env
    volumes:
      - ./api:/api
      - /app/node_modules/
    ports:
      - 3000:3000

  db:
    image: mongo:latest
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}

  mongo-express:
    image: mongo-express:latest
    ports:
      - 8081:8081
    env_file: .env
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGODB_USER}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGODB_PASSWORD}
      - ME_CONFIG_MONGODB_SERVER=db
    depends_on:
      - db

  e2e:
    build: 
      context: ./e2e
    volumes:
      - ./e2e:/e2e
      - /e2e/node_modules
    ports:
      - 9323:9323
      - 6006:6006
    depends_on:
      - app
    network_mode: host
    container_name: e2e_demo
    profiles: ['test']
