version: "3.8"

services:
  app:
    build: 
      context: ./app
    env_file: .env
    volumes:
      - ./app:/app
      - /app/node_modules/
    ports:
      - 3000:3000

  api:
    build:
      context: ./api
    env_file: .env
    volumes:
      - ./api:/api
      - /app/node_modules/
    ports:
      - 5000:5000

  db:
    image: mongo:latest
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - mongodb-config:/data/configdb
      - mongodb-data:/data/db
      - mongodb-dumps:/data/dumps
      - mongodb-backups:/data/backups

  mongo-express:
    image: mongo-express:latest
    ports:
      - 8081:8081
    env_file: .env
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGODB_USER}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGODB_PASSWORD}
      - ME_CONFIG_MONGODB_SERVER=db
    depends_on:
      - db

  e2e:
    build: 
      context: ./e2e
    volumes:
      - ./e2e:/e2e
      - /e2e/node_modules
    ports:
      - 9323:9323
      - 6006:6006
    depends_on:
      - app
    network_mode: host
    container_name: e2e_demo
    profiles: ['test']

volumes:
  mongodb-config:
    external: false
  mongodb-data:
    external: false
  mongodb-dumps:
    external: false
  mongodb-backups:
    external: false