version: "3.8"

services:
  app:
    build: 
      context: ./app
    volumes:
      - ./app:/app
      - /app/node_modules/
    ports:
      - 3000:3000

  e2e:
    build: 
      context: ./e2e
    volumes:
      - ./e2e:/e2e
      - /e2e/node_modules
    ports:
      - 9323:9323
    depends_on:
      - app
    network_mode: host
    container_name: e2e_demo
